name: Build And Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name:
        run:
          - echo "::set-env name=CGO_ENABLED::0"
          - echo "::set-env name=GO111MODULE::on"
          - echo "::set-env name=GOARCH::amd64"
          - echo "::set-env name=GOOS::linux"
      - name: Build
        run: go build -o dist/ssh-microservice cmd/main.go